fieldLayouts:
  38636920-a75d-4e5a-bd76-c8111234a225:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 04d1ef46-2fe8-4c27-9891-799a13eb7735
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 863f54f0-6c7e-4b72-a816-e36ce9fe8785
        userCondition: null
fs: uploads
handle: uploads
name: Uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: ''
