defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  7a77143a-8307-4818-b2e9-bcaa093e0cc0: # Pharmalys
    enabledByDefault: true
    hasUrls: true
    template: home.twig
    uriFormat: __home__
type: single
